### PR TITLE
Add replaceOnInsert functionality

### PR DESCRIPTION
**Pull request by jcoveney**
This is something we use at twitter which was removed when we left maple. I basically just made this pr: https://github.com/Cascading/maple/pull/45 work in cascading-jdbc. Is backwards compatible (just adds a new constructor).

### CODE REVIEW

**Comment by fs111** [comment]
Thanks. Since this is a mysql specific feature, it should not be implemented in cascading-jdbc-core, but in a subclass in cascading-jdbc-mysql. We are doing that already for oracle specifics in cascading-jdbc-oracle. Could you change that?

One more thing: before I can accept your contribution, you have to sign the contributor agreement: http://files.concurrentinc.com/agreements/Concurrent_Contributor_Agreement.doc and  send it to me andre [at] concurrentinc [dot] com. Thx!

**Comment by jcoveney** [comment]
Ack, I just saw this. Somehow I never got the email from github. Will fix this shortly.

Question about the contributor agreement: is "signing" it online fine, or do I need to print and scan?

**Comment by cwensel** [comment]
We already have an agreement signed with Twitter.

**Comment by jcoveney** [comment]
Cool.

So I've been looking at factoring this how you said, @fs111, and it doesn't seem factored to make it possible to do with a bit of code duplication (though there are worse things, of course).

I suppose I can make a MySqlDBOutputFormat which will call super.constructInsertQuery() and then appends mine to the end, though this is of course fragile.

The slightly bigger issue is DBConfiguration. This is currently the only layer of indirection I see to get/set things like replaceOnInsert. And since the DBOutputFormat is currently instantiated via reflection, there is no good way to set anything.

So I'm all for modularity, but the current approach seems like it precludes it in my case. I can try to do a more aggressive refactor, but my question is 1) is there in fact a better way to do this that I am not seeing? and 2) would such a refactor even be accepted?

**Comment by jcoveney** [comment]
Hmm I may have a lighter weight in-between approach. Will see if it works.

**Comment by jcoveney** [comment]
Ok, I think I have an approach which maximizes code reuse while allowing this to be set. The one fragile piece is if the DBOutputFormat changes the constructInsertQuery method in some weird way. There should be tests for this, but we need a MysqlFactory to facilitate that, it seems, and that seemed a bit out of scope. Would like to validate this approach.

**Comment by fs111** [comment]
Hey, I just integrated your changes into cascading-jdbc. Could you give cascading-jdbc-mysql-2.5.2-wip-68 a try and let me know, if something goes wrong?

Thanks!

**Comment by jcoveney** [comment]
Will do this today.

**Comment by jcoveney** [comment]
Early validation looks good. Am in the process of getting people to do more integration validation.

**Comment by fs111** [comment]
If you don't tell me not to, I am going to do a release of cascading-jdbc with this change tomorrow morning (Berlin time).

**Comment by fs111** [comment]
2.5.2 is released.

**Comment by jcoveney** [comment]
For what it's worth, we tested internally and looks good. It just took longer than expected. Thanks, @fs111 !

**Pull request closed without merging**
